framework:
  secret: 'symfony'

  http_method_override: false
  router:
    strict_requirements: true

  assets: false
  templating:
    engines: ['twig']

  session:
    handler_id: 'session.handler.native_file'
    save_path:  '%kernel.project_dir%/var/sessions'
    name:       's'
