app:
  path:     /
  defaults: { _controller: 'Oauth\Controller\ProfileController::get' }

app_login:
  path:     /login
  defaults: { _controller: 'Oauth\Controller\Login\LoginController::get' }
  methods:  [GET]

app_login_begin:
  path:     /login
  defaults: { _controller: 'Oauth\Controller\Login\LoginBeginController::post' }
  methods:  [POST]

app_login_complete:
  path:     /login/complete
  defaults: { _controller: 'Oauth\Controller\Login\LoginCompleteController::get' }

app_logout:
  path:     /logout
  defaults: { _controller: 'Oauth\Controller\Logout\LogoutController::post' }
  methods:  [POST]
